### ISSUE TITLE
Integration with Netlify Status page

### ISSUE THREAD

**Issue by ZoltanVeres** [stefanjudis/netlify-menubar#11]
Hey, this is a super idea and an even better execution.

I think it would be awesome to grab somehow the data from https://www.netlifystatus.com/ and display if it's there's an issue with Netlify's infra. Netlify status is hosted on https://www.statuspage.io, they have an API but i think in order to use it, we need to request an API from Netlify.

**Comment by stefanjudis** [comment]
I like that, not sure if we're able to get an API key though.

Maybe @philhawksworth can give some insights? 😊

**Comment by philhawksworth** [comment]
Interesting. Let me ask wiser people.

**Comment by philhawksworth** [comment]
You can consume a feed of the status feed. Perhaps that would be sufficient?:

https://www.netlifystatus.com/history.atom
https://www.netlifystatus.com/history.rss

**Comment by stefanjudis** [comment]
Right! 🙈 Didn't think of this! 👍🏻

@ZoltanVeres are you up for giving it a shot? That would be fabulous! 😊

*(I'm there to help – if needed)*

**Comment by stefanjudis** [comment]
Sweet! :) yeah - it's not critical. take you time. :)

**Comment by ZoltanVeres** [comment]
@stefanjudis I'm not gonna be able to work on this in the foreseeable future. But i do thing it would be a very useful feature

**Comment by stefanjudis** [comment]
No worries. Thanks for the suggestion. :)

**Comment by ZoltanVeres** [comment]
@stefanjudis My humble opinion is that it if something new is getting published to the netlify status rss, chances are that you wanna know immediately, because it can effect you site too. I think it has to be a notification. What would be ideal is to have a different color or an icon if there's an active status published in netlify status, but honestly having a new section in the menu for netlify status would do the trick too

**Comment by adamwatters** [comment]
@stefanjudis this is awesome! one less open browser tab to get distracted by 👍 
if it's ok with you and @ZoltanVeres I'd like to take a crack at adding a notifications for the netlify status rss

**Comment by stefanjudis** [comment]
Sure! 🎉 Go for it! :)

**Comment by adamwatters** [comment]
![image](https://user-images.githubusercontent.com/7673611/53531915-bf5b2a00-3ac2-11e9-9ef8-dcfcef3ad372.png)

got this notification today 😎

**Comment by stefanjudis** [comment]
Shipped. :)
