### ISSUE TITLE
Only works with owned sites

### ISSUE THREAD

**Issue by pugson** [stefanjudis/netlify-menubar#16]
Hello 💖️

I noticed that the app is not displaying sites that you're a collaborator to, only ones owned by yourself. Wish it would show both kinds!

**Comment by stefanjudis** [comment]
That's a nice idea! I'm not sure it's possible though. Looking at the [API docs](https://open-api.netlify.com/) i'm not sure how to get these.

Is that technically possible @philhawksworth?
