### ISSUE TITLE
paginate deploys listing

### ISSUE THREAD

**Issue by fool** [stefanjudis/netlify-menubar#20]
Hi Stefan!  I work with Netlify tech support and your menubar just caused a bit of a problem on our service.  Our team sees that you seem to use the Deploys endpoint (https://open-api.netlify.com/#operation/listSiteDeploys) without paginating, so we return 100 at a time.  Could you please paginate (use parameters on your requests like `?page=1&per_page=15`) to avoid overloading our API?

Let me know if you have any questions!

**Comment by stefanjudis** [comment]
@fool 

Hey Chris. Thanks for reaching out.

> caused a bit of a problem on our service

I hope it was not too bad. :/

I'll try to tackle this ASAP, most likely tmrw though. Should I additionally set a custom header or something, so that you know you're dealing with netlify-menubar?

**Comment by fool** [comment]
No outage was caused but some alarmed SRE's (who were already awake) went
on high alert.

You set a custom user agent already which is how we figured out the source
:)  That's sufficient and much appreciated!

**Comment by stefanjudis** [comment]
Alright, sorry about that then (it's running like this for over a year 🙈) I'll have a look tmrw then. And will let you know when I pushed another release. Most likely it will take a little bit then until the update is propagated to all clients. :)

**Comment by stefanjudis** [comment]
In theory, this should be fixed now. :) But I something broke due to a dep update... Let's see. The updated endpoint is in latest release line. Let's see when it gets down to all the users. :) 

I'm closing here for now. :)
