### ISSUE TITLE
Menu bar icon looks transparent on white menu bar

### ISSUE THREAD

**Issue by viviangb** [stefanjudis/netlify-menubar#7]
Here's the main issue:
![2019-01-12 20 11 20](https://user-images.githubusercontent.com/7389358/51079868-4769a980-16a6-11e9-85ec-e70fcab08f7e.gif)

I'm on MacOS High Sierra btw.

**Comment by viviangb** [comment]
@stefanjudis I just noticed that there's a setting on MacOS for making the menu bar dark:

![image](https://user-images.githubusercontent.com/7389358/51079878-9b748e00-16a6-11e9-8f3c-cc021efe6268.png)

When I activate it, the menu bar icon looks great! 

![image](https://user-images.githubusercontent.com/7389358/51079879-a8917d00-16a6-11e9-94ac-fa20d4179f0c.png)

So, maybe we need to check if that setting is activated or not?

**Comment by stefanjudis** [comment]
Hey @viviangb,

thanks for bringing this up. :) That's odd and I have to admit that I didn't test it properly for the mac default/light mode. Shame on me. :/

If you want to you can fix it yourself? the icons are located in this folder -> https://github.com/stefanjudis/netlify-menubar/tree/master/media.

And these are the SVG base icons.

[icons.zip](https://github.com/stefanjudis/netlify-menubar/files/2752673/icons.zip)

I would assume we're running into this issue? 

https://stackoverflow.com/questions/41664208/electron-tray-icon-change-depending-on-dark-theme

what do you think?

**Comment by viviangb** [comment]
@stefanjudis yep can do, I'll try to submit a fix before the end of the weekend.

**Comment by viviangb** [comment]
hey @stefanjudis, just submitted a PR, let me know what you think.

**Comment by viviangb** [comment]
Btw, here's the updated icons. 

I edited them in Sketch but my design skills are somewhat limited 😅

[UpdatedIcons.zip](https://github.com/stefanjudis/netlify-menubar/files/2752701/UpdatedIcons.zip)

**Comment by stefanjudis** [comment]
Fixed with https://github.com/stefanjudis/netlify-menubar/pull/8
